[keybindings]
" " = "playpause"
"n" = "next"
"p" = "previous"
"Esc" = "back"

[saved_state]
volume = 75
repeat = "playlist"

[theme]
playing_selected = "#ffffff"
title = "black"
highlight = "black"
highlight_bg = "dark magenta"
